version: '3'
services:
  postgres_library_mvc:
    container_name: postgres_library_mvc
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: library_spring_mvc
    ports:
      - "5432:5432"
  library_spring_mvc:
    build: ./
    container_name: library_spring_mvc
    image: library_spring_mvc
    depends_on:
      - postgres_library_mvc
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_library_mvc:5432/library_spring_mvc
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    ports:
      - "8080:8080"
